"""Tests for masterbook/tools/assemble.py."""
import sys

import pytest

from assemble import parse_frontmatter, FrontmatterError


def test_parse_frontmatter_basic():
    text = """---
id: tier-1/example
name: Example
tier: 1
---

body line 1
body line 2
"""
    fm, body = parse_frontmatter(text)
    assert fm["id"] == "tier-1/example"
    assert fm["tier"] == 1
    assert body.strip() == "body line 1\nbody line 2"


def test_parse_frontmatter_missing_raises():
    with pytest.raises(FrontmatterError):
        parse_frontmatter("no frontmatter here\n")


def test_parse_frontmatter_unterminated_raises():
    with pytest.raises(FrontmatterError):
        parse_frontmatter("---\nid: x\n# never closes\n")


from pathlib import Path

from assemble import expand_module_list


def test_expand_glob_tier1(mini_masterbook):
    result = expand_module_list(mini_masterbook, ["tier-1/*"])
    assert [p.name for p in result] == ["example.md"]


def test_expand_explicit_module(mini_masterbook):
    result = expand_module_list(mini_masterbook, ["tier-2/optional"])
    assert [p.name for p in result] == ["optional.md"]


def test_expand_dedupes_and_orders(mini_masterbook):
    # Tier-1 always comes before tier-2; duplicates collapse.
    result = expand_module_list(
        mini_masterbook, ["tier-2/optional", "tier-1/*", "tier-1/example"]
    )
    rels = [str(p.relative_to(mini_masterbook)) for p in result]
    assert rels == ["tier-1/example.md", "tier-2/optional.md"]


def test_expand_unknown_raises(mini_masterbook):
    with pytest.raises(FileNotFoundError):
        expand_module_list(mini_masterbook, ["tier-2/nonexistent"])


from assemble import compute_module_hash


def test_hash_stable_across_line_endings(tmp_path):
    p = tmp_path / "m.md"
    p.write_bytes(b"---\nid: x\n---\nbody\n")
    h1 = compute_module_hash(p)
    p.write_bytes(b"---\r\nid: x\r\n---\r\nbody\r\n")
    h2 = compute_module_hash(p)
    assert h1 == h2


def test_hash_changes_on_content_change(tmp_path):
    p = tmp_path / "m.md"
    p.write_text("---\nid: x\n---\nA\n")
    h1 = compute_module_hash(p)
    p.write_text("---\nid: x\n---\nB\n")
    h2 = compute_module_hash(p)
    assert h1 != h2


def test_hash_is_12_hex_chars(tmp_path):
    p = tmp_path / "m.md"
    p.write_text("---\nid: x\n---\nbody\n")
    h = compute_module_hash(p)
    assert len(h) == 12
    assert all(c in "0123456789abcdef" for c in h)


from assemble import render_claude_md


def test_render_includes_banner_and_frontmatter(mini_masterbook, sample_project):
    out = render_claude_md(
        masterbook_root=mini_masterbook,
        project_source=sample_project / "CLAUDE.source.md",
        version="0.0.1",
        built="2026-05-02",
    )
    assert "# Generated by recordkeeper" in out
    assert "Edit `CLAUDE.source.md` instead" in out
    assert "built: 2026-05-02" in out
    assert "version: 0.0.1" in out
    assert "tier-1/example@sha:" in out
    assert "tier-2/optional@sha:" in out


def test_render_concatenates_module_bodies(mini_masterbook, sample_project):
    out = render_claude_md(
        masterbook_root=mini_masterbook,
        project_source=sample_project / "CLAUDE.source.md",
        version="0.0.1",
        built="2026-05-02",
    )
    assert "# Example tier-1" in out
    assert "# Optional tier-2" in out
    assert "Sample project body" in out


def test_render_tier1_before_tier2(mini_masterbook, sample_project):
    out = render_claude_md(
        masterbook_root=mini_masterbook,
        project_source=sample_project / "CLAUDE.source.md",
        version="0.0.1",
        built="2026-05-02",
    )
    assert out.index("# Example tier-1") < out.index("# Optional tier-2")


import json
from assemble import merge_settings


def test_merge_baseline_only(mini_masterbook):
    out = merge_settings(
        masterbook_root=mini_masterbook,
        substrates=[],
        permissions_extra=[],
    )
    assert "Read" in out["permissions"]["allow"]
    assert "Bash(git *)" in out["permissions"]["allow"]


def test_merge_dedupes_permissions(mini_masterbook):
    out = merge_settings(
        masterbook_root=mini_masterbook,
        substrates=[],
        permissions_extra=["Read", "Bash(pytest *)"],
    )
    assert out["permissions"]["allow"].count("Read") == 1
    assert "Bash(pytest *)" in out["permissions"]["allow"]


def test_merge_appends_top_level_fragment_permissions(mini_masterbook):
    """Every top-level fragment contributes its permissions.allow (always-on)."""
    frag = mini_masterbook / "settings-fragments" / "extra.json"
    frag.write_text(json.dumps({"permissions": {"allow": ["Bash(uv *)"]}}))
    out = merge_settings(
        masterbook_root=mini_masterbook,
        substrates=[],
        permissions_extra=[],
    )
    assert "Bash(uv *)" in out["permissions"]["allow"]


def test_merge_settings_reads_hooks_from_top_level_fragments(mini_masterbook):
    """Every top-level settings-fragment with a hooks block contributes entries (always-on)."""
    (mini_masterbook / "settings-fragments" / "shell-hygiene-hook.json").write_text(json.dumps({
        "hooks": {
            "PreToolUse": [
                {"matcher": "Bash", "hooks": [{"type": "command", "command": "/x/shell.py"}]}
            ]
        }
    }))
    out = merge_settings(
        masterbook_root=mini_masterbook,
        substrates=[],
        permissions_extra=[],
    )
    pre = out["hooks"]["PreToolUse"]
    assert any(e["matcher"] == "Bash" and e["hooks"][0]["command"] == "/x/shell.py" for e in pre)


def test_merge_settings_reads_hooks_from_substrate_fragments(mini_masterbook):
    """A substrate listed in `substrates` contributes its fragment's hooks."""
    sub = mini_masterbook / "substrate" / "demo"
    sub.mkdir(parents=True)
    (sub / "module.md").write_text(
        "---\nid: substrate/demo\nname: D\ntier: substrate\ndefault: false\nsummary: s\n---\nbody\n"
    )
    (sub / "settings-fragment.json").write_text(json.dumps({
        "hooks": {
            "PreToolUse": [
                {"matcher": "Edit|Write", "hooks": [{"type": "command", "command": "/x/sub.py"}]}
            ]
        }
    }))
    out = merge_settings(
        masterbook_root=mini_masterbook,
        substrates=["demo"],
        permissions_extra=[],
    )
    pre = out["hooks"]["PreToolUse"]
    assert any(e["matcher"] == "Edit|Write" and e["hooks"][0]["command"] == "/x/sub.py" for e in pre)


def test_merge_settings_substrate_skipped_when_not_listed(mini_masterbook):
    """Substrate fragment NOT listed in `substrates` is ignored."""
    sub = mini_masterbook / "substrate" / "demo"
    sub.mkdir(parents=True)
    (sub / "settings-fragment.json").write_text(json.dumps({
        "hooks": {
            "PreToolUse": [
                {"matcher": "Edit", "hooks": [{"type": "command", "command": "/x/sub.py"}]}
            ]
        }
    }))
    out = merge_settings(
        masterbook_root=mini_masterbook,
        substrates=[],
        permissions_extra=[],
    )
    assert "hooks" not in out or not any(
        e.get("matcher") == "Edit" and e["hooks"][0]["command"] == "/x/sub.py"
        for e in out.get("hooks", {}).get("PreToolUse", [])
    )


def test_merge_settings_dedupes_hook_entries(mini_masterbook):
    """Same (event, matcher, command) from two fragments collapses to one."""
    (mini_masterbook / "settings-fragments" / "a.json").write_text(json.dumps({
        "hooks": {
            "PreToolUse": [
                {"matcher": "Bash", "hooks": [{"type": "command", "command": "/x/dup.py"}]}
            ]
        }
    }))
    (mini_masterbook / "settings-fragments" / "b.json").write_text(json.dumps({
        "hooks": {
            "PreToolUse": [
                {"matcher": "Bash", "hooks": [{"type": "command", "command": "/x/dup.py"}]}
            ]
        }
    }))
    out = merge_settings(
        masterbook_root=mini_masterbook,
        substrates=[],
        permissions_extra=[],
    )
    dup_entries = [e for e in out["hooks"]["PreToolUse"]
                   if e.get("matcher") == "Bash" and e["hooks"][0]["command"] == "/x/dup.py"]
    assert len(dup_entries) == 1


def test_merge_settings_substrate_fragment_also_contributes_permissions(mini_masterbook):
    """Substrate fragments can carry permissions.allow too."""
    sub = mini_masterbook / "substrate" / "demo"
    sub.mkdir(parents=True)
    (sub / "settings-fragment.json").write_text(json.dumps({
        "permissions": {"allow": ["Bash(custom *)"]}
    }))
    out = merge_settings(
        masterbook_root=mini_masterbook,
        substrates=["demo"],
        permissions_extra=[],
    )
    assert "Bash(custom *)" in out["permissions"]["allow"]


from assemble import emit_agents_md, deploy_commands


def test_emit_agents_md_creates_symlink(tmp_path):
    claude = tmp_path / "CLAUDE.md"
    claude.write_text("hello")
    agents = emit_agents_md(claude)
    assert agents.exists()
    # Should resolve to CLAUDE.md content
    assert agents.read_text() == "hello"


def test_deploy_commands_copies_declared(mini_masterbook, tmp_path):
    project = tmp_path / "proj"
    project.mkdir()
    deploy_commands(
        masterbook_root=mini_masterbook,
        project_path=project,
        commands=["rebuild"],
        substrates=[],
    )
    assert (project / ".claude" / "commands" / "rebuild.md").is_file()


def test_deploy_commands_unknown_raises(mini_masterbook, tmp_path):
    project = tmp_path / "proj"
    project.mkdir()
    with pytest.raises(FileNotFoundError):
        deploy_commands(
            masterbook_root=mini_masterbook,
            project_path=project,
            commands=["nonexistent"],
            substrates=[],
        )


def test_deploy_commands_walks_substrate(mini_masterbook, tmp_path):
    """Substrate-bundled commands are deployed when the substrate is opted in."""
    sub = mini_masterbook / "substrate" / "demo-paperwork"
    (sub / "commands").mkdir(parents=True)
    (sub / "commands" / "do-thing.md").write_text(
        "---\ndescription: do a thing\n---\n\n# /do-thing\nBody.\n"
    )
    project = tmp_path / "proj"
    project.mkdir()
    deploy_commands(
        masterbook_root=mini_masterbook,
        project_path=project,
        commands=[],
        substrates=["demo-paperwork"],
    )
    assert (project / ".claude" / "commands" / "do-thing.md").is_file()


def test_deploy_commands_collision_substrate_vs_toplevel(mini_masterbook, tmp_path):
    """Substrate command shadowing a top-level command name raises RuntimeError."""
    sub = mini_masterbook / "substrate" / "demo-paperwork"
    (sub / "commands").mkdir(parents=True)
    # `rebuild.md` already exists at masterbook/commands/rebuild.md in mini fixture.
    (sub / "commands" / "rebuild.md").write_text(
        "---\ndescription: shadow rebuild\n---\n\nBody.\n"
    )
    project = tmp_path / "proj"
    project.mkdir()
    with pytest.raises(RuntimeError, match="rebuild.md"):
        deploy_commands(
            masterbook_root=mini_masterbook,
            project_path=project,
            commands=["rebuild"],
            substrates=["demo-paperwork"],
        )


def test_deploy_commands_collision_substrate_vs_substrate(mini_masterbook, tmp_path):
    """Two substrates with the same command filename raise RuntimeError."""
    sub_a = mini_masterbook / "substrate" / "demo-a"
    sub_b = mini_masterbook / "substrate" / "demo-b"
    (sub_a / "commands").mkdir(parents=True)
    (sub_b / "commands").mkdir(parents=True)
    (sub_a / "commands" / "shared.md").write_text(
        "---\ndescription: a\n---\n\nBody.\n"
    )
    (sub_b / "commands" / "shared.md").write_text(
        "---\ndescription: b\n---\n\nBody.\n"
    )
    project = tmp_path / "proj"
    project.mkdir()
    with pytest.raises(RuntimeError, match="shared.md"):
        deploy_commands(
            masterbook_root=mini_masterbook,
            project_path=project,
            commands=[],
            substrates=["demo-a", "demo-b"],
        )


from assemble import check_length_budget, check_mtime_inversion


def test_length_budget_under_passes():
    short = "word " * 100
    assert check_length_budget(short, budget_words=200) is None


def test_length_budget_over_returns_warning():
    long = "word " * 5000
    msg = check_length_budget(long, budget_words=4000)
    assert msg is not None
    assert "exceeds" in msg


def test_mtime_check_artifact_newer_warns(tmp_path):
    src = tmp_path / "CLAUDE.source.md"
    art = tmp_path / "CLAUDE.md"
    src.write_text("source")
    # Force art to be newer than src
    art.write_text("artifact")
    import os, time
    older = time.time() - 100
    os.utime(src, (older, older))
    msg = check_mtime_inversion(src, art)
    assert msg is not None
    assert "hand-edited" in msg


def test_mtime_check_artifact_older_passes(tmp_path):
    src = tmp_path / "CLAUDE.source.md"
    art = tmp_path / "CLAUDE.md"
    art.write_text("artifact")
    import os, time
    older = time.time() - 100
    os.utime(art, (older, older))
    src.write_text("source")
    assert check_mtime_inversion(src, art) is None


import subprocess

ASSEMBLE = Path(__file__).resolve().parent.parent / "tools" / "assemble.py"
REPO_ROOT = ASSEMBLE.parent.parent


def test_assemble_cli_end_to_end(mini_masterbook, sample_project):
    # The CLI takes (masterbook_root, project_path) as args and writes artifacts in place.
    result = subprocess.run(
        [sys.executable, str(ASSEMBLE), str(mini_masterbook), str(sample_project)],
        cwd=str(Path(__file__).resolve().parents[1]),
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stderr

    claude = sample_project / "CLAUDE.md"
    agents = sample_project / "AGENTS.md"
    settings = sample_project / ".claude" / "settings.json"
    rebuild_cmd = sample_project / ".claude" / "commands" / "rebuild.md"

    assert claude.is_file()
    assert agents.exists()
    assert settings.is_file()
    assert rebuild_cmd.is_file()

    text = claude.read_text()
    assert "# Example tier-1" in text
    assert "# Optional tier-2" in text
    assert "Sample project body" in text
    assert "built:" in text

    import json
    s = json.loads(settings.read_text())
    assert "Bash(pytest *)" in s["permissions"]["allow"]  # from permissions_extra


from assemble import expand_substrate_list


def test_expand_substrate_list_resolves_known(mini_masterbook):
    """A substrate name resolves to substrate/<name>/module.md."""
    sub = mini_masterbook / "substrate" / "demo"
    sub.mkdir(parents=True)
    mod = sub / "module.md"
    mod.write_text(
        "---\nid: substrate/demo\nname: D\ntier: substrate\ndefault: false\nsummary: s\n---\nbody\n"
    )
    result = expand_substrate_list(mini_masterbook, ["demo"])
    assert result == [mod]


def test_expand_substrate_list_unknown_raises(mini_masterbook):
    """Unknown substrate name raises FileNotFoundError."""
    with pytest.raises(FileNotFoundError):
        expand_substrate_list(mini_masterbook, ["nonexistent"])


def test_expand_substrate_list_preserves_order(mini_masterbook):
    """Declaration order is preserved (deterministic deploy)."""
    for name in ("first", "second"):
        sub = mini_masterbook / "substrate" / name
        sub.mkdir(parents=True)
        (sub / "module.md").write_text(
            f"---\nid: substrate/{name}\nname: N\ntier: substrate\ndefault: false\nsummary: s\n---\nbody\n"
        )
    result = expand_substrate_list(mini_masterbook, ["second", "first"])
    assert [p.parent.name for p in result] == ["second", "first"]


from assemble import deploy_hooks


def test_deploy_hooks_copies_baseline(mini_masterbook, tmp_path):
    """All .py in masterbook/hooks/ get copied to project/.claude/hooks/."""
    hooks_src = mini_masterbook / "hooks"
    hooks_src.mkdir(exist_ok=True)
    (hooks_src / "a.py").write_text("print('a')\n")
    (hooks_src / "b.py").write_text("print('b')\n")
    project = tmp_path / "proj"
    project.mkdir()
    deployed = deploy_hooks(masterbook_root=mini_masterbook, substrates=[], project_path=project)
    assert (project / ".claude" / "hooks" / "a.py").is_file()
    assert (project / ".claude" / "hooks" / "b.py").is_file()
    assert sorted(p.name for p in deployed) == ["a.py", "b.py"]


def test_deploy_hooks_copies_substrate(mini_masterbook, tmp_path):
    """Substrate hooks get copied when the substrate is listed."""
    sub_hooks = mini_masterbook / "substrate" / "demo" / "hooks"
    sub_hooks.mkdir(parents=True)
    (sub_hooks / "sub.py").write_text("print('sub')\n")
    project = tmp_path / "proj"
    project.mkdir()
    deploy_hooks(masterbook_root=mini_masterbook, substrates=["demo"], project_path=project)
    assert (project / ".claude" / "hooks" / "sub.py").is_file()


def test_deploy_hooks_skips_substrate_when_not_listed(mini_masterbook, tmp_path):
    """Substrate hooks NOT in the substrates list are not copied."""
    sub_hooks = mini_masterbook / "substrate" / "demo" / "hooks"
    sub_hooks.mkdir(parents=True)
    (sub_hooks / "sub.py").write_text("print('sub')\n")
    project = tmp_path / "proj"
    project.mkdir()
    deploy_hooks(masterbook_root=mini_masterbook, substrates=[], project_path=project)
    assert not (project / ".claude" / "hooks" / "sub.py").exists()


def test_deploy_hooks_collision_raises(mini_masterbook, tmp_path):
    """Filename collision between baseline and substrate raises RuntimeError."""
    (mini_masterbook / "hooks").mkdir(exist_ok=True)
    (mini_masterbook / "hooks" / "dup.py").write_text("print('a')\n")
    sub_hooks = mini_masterbook / "substrate" / "demo" / "hooks"
    sub_hooks.mkdir(parents=True)
    (sub_hooks / "dup.py").write_text("print('b')\n")
    project = tmp_path / "proj"
    project.mkdir()
    with pytest.raises(RuntimeError) as exc:
        deploy_hooks(masterbook_root=mini_masterbook, substrates=["demo"], project_path=project)
    assert "dup.py" in str(exc.value)


def test_deploy_hooks_preserves_executable_bit(mini_masterbook, tmp_path):
    """copy2 preserves executable bit (matters for hooks Claude Code runs)."""
    import os, stat
    hooks_src = mini_masterbook / "hooks"
    hooks_src.mkdir(exist_ok=True)
    src = hooks_src / "exe.py"
    src.write_text("#!/usr/bin/env python3\nprint('x')\n")
    os.chmod(src, 0o755)
    project = tmp_path / "proj"
    project.mkdir()
    deploy_hooks(masterbook_root=mini_masterbook, substrates=[], project_path=project)
    dst = project / ".claude" / "hooks" / "exe.py"
    assert dst.is_file()
    assert dst.stat().st_mode & stat.S_IXUSR


def test_render_appends_substrate_body(mini_masterbook, sample_project):
    """Substrate bodies appear after tier modules in assembled CLAUDE.md."""
    sub = mini_masterbook / "substrate" / "demo"
    sub.mkdir(parents=True)
    (sub / "module.md").write_text(
        "---\nid: substrate/demo\nname: D\ntier: substrate\ndefault: false\nsummary: s\n---\n"
        "# Demo substrate body marker\n"
    )
    src = sample_project / "CLAUDE.source.md"
    src.write_text(
        "---\nmasterbook:\n  modules:\n    - tier-1/*\n  substrates:\n    - demo\n  permissions_extra: []\n  commands: []\n---\n\n"
        "Project body.\n"
    )
    out = render_claude_md(
        masterbook_root=mini_masterbook,
        project_source=src,
        version="0.0.1",
        built="2026-05-12",
    )
    assert "# Demo substrate body marker" in out
    # Substrates appear after tier modules but before project body.
    assert out.index("# Example tier-1") < out.index("# Demo substrate body marker")
    assert out.index("# Demo substrate body marker") < out.index("Project body.")


def test_assemble_with_substrate_end_to_end(tmp_path):
    """Full assembly of a project that opts into store-write-approval.

    Verifies:
      - settings.json has 5 hook entries (3 baseline + 2 substrate).
      - .claude/hooks/ contains all 5 .py files.
      - CLAUDE.md includes the substrate body marker.
      - All deployed hook files are syntactically valid Python.
    """
    import shutil
    src_root = Path(__file__).resolve().parent / "fixtures" / "with_substrate"
    mb_src = src_root / "masterbook"
    proj_src = src_root / "project"
    mb_dst = tmp_path / "mb"
    proj_dst = tmp_path / "proj"
    shutil.copytree(mb_src, mb_dst)
    shutil.copytree(proj_src, proj_dst)

    result = subprocess.run(
        [sys.executable, str(ASSEMBLE), str(mb_dst), str(proj_dst)],
        cwd=str(REPO_ROOT),
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stderr

    # Settings has all 5 hook entries.
    settings = json.loads((proj_dst / ".claude" / "settings.json").read_text())
    commands = []
    for event_entries in settings.get("hooks", {}).values():
        for entry in event_entries:
            for sub in entry["hooks"]:
                commands.append(sub["command"])
    expected_baseline_basenames = {
        "pre_bash_shell_hygiene.py",
        "pre_tool_use_secrets.py",
        "stop_session_log.py",
    }
    expected_substrate_basenames = {
        "pre_store_write_protection.py",
        "pre_sentinel_no_self_touch.py",
    }
    deployed_basenames = {Path(c).name for c in commands}
    assert expected_baseline_basenames <= deployed_basenames, (
        f"missing baseline hooks; got {deployed_basenames}"
    )
    assert expected_substrate_basenames <= deployed_basenames, (
        f"missing substrate hooks; got {deployed_basenames}"
    )

    # All 5 hook files were copied to .claude/hooks/.
    deployed_dir = proj_dst / ".claude" / "hooks"
    actual_files = {p.name for p in deployed_dir.glob("*.py")}
    assert (expected_baseline_basenames | expected_substrate_basenames) <= actual_files

    # Each deployed hook is syntactically valid Python.
    import ast as _ast
    for p in deployed_dir.glob("*.py"):
        _ast.parse(p.read_text())

    # Substrate body is inlined in CLAUDE.md.
    claude_text = (proj_dst / "CLAUDE.md").read_text()
    assert "Recovery section to verify body inlining" in claude_text


def test_assemble_with_session_paperwork_end_to_end(tmp_path):
    """Full assembly of a project that opts into session-paperwork.

    Verifies:
      - .claude/commands/begin-session.md and debrief.md deployed.
      - .claude/hooks/session_stop_log_timing.py deployed and parses as Python.
      - settings.json hooks.Stop block includes the substrate's entry.
      - CLAUDE.md includes the substrate body marker.
    """
    import shutil
    src_root = Path(__file__).resolve().parent / "fixtures" / "with_session_paperwork"
    mb_src = src_root / "masterbook"
    proj_src = src_root / "project"
    mb_dst = tmp_path / "mb"
    proj_dst = tmp_path / "proj"
    shutil.copytree(mb_src, mb_dst)
    shutil.copytree(proj_src, proj_dst)

    result = subprocess.run(
        [sys.executable, str(ASSEMBLE), str(mb_dst), str(proj_dst)],
        cwd=str(REPO_ROOT),
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stderr

    # Commands deployed.
    deployed_cmds = proj_dst / ".claude" / "commands"
    assert (deployed_cmds / "begin-session.md").is_file()
    assert (deployed_cmds / "debrief.md").is_file()

    # Hook deployed and syntactically valid.
    deployed_hook = proj_dst / ".claude" / "hooks" / "session_stop_log_timing.py"
    assert deployed_hook.is_file()
    import ast as _ast
    _ast.parse(deployed_hook.read_text())

    # settings.json includes the Stop entry pointing at the deployed hook.
    settings = json.loads((proj_dst / ".claude" / "settings.json").read_text())
    stop_entries = settings.get("hooks", {}).get("Stop", [])
    commands_found = []
    for entry in stop_entries:
        for sub in entry.get("hooks", []):
            commands_found.append(sub.get("command", ""))
    assert any("session_stop_log_timing.py" in c for c in commands_found), (
        f"Stop hook entry not found; got: {commands_found}"
    )

    # CLAUDE.md includes the substrate body marker.
    claude_text = (proj_dst / "CLAUDE.md").read_text()
    assert "Session paperwork — fixture body marker" in claude_text


def test_assemble_rejects_paperwork_enforcement_without_session_paperwork(tmp_path):
    """Assembling a project that opts into paperwork-enforcement WITHOUT session-paperwork
    fails with a clean diagnostic."""
    import sys
    from pathlib import Path
    ASSEMBLE = Path(__file__).resolve().parent.parent / "tools"
    if str(ASSEMBLE) not in sys.path:
        sys.path.insert(0, str(ASSEMBLE))
    import assemble

    REPO_ROOT = Path(__file__).resolve().parent.parent
    masterbook_root = REPO_ROOT

    project = tmp_path / "proj"
    project.mkdir()
    (project / "CLAUDE.source.md").write_text(
        "---\n"
        "masterbook:\n"
        "  modules: []\n"
        "  substrates: [paperwork-enforcement]\n"
        "  permissions_extra: []\n"
        "  commands: []\n"
        "---\n"
        "body\n"
    )
    with pytest.raises(assemble.SubstrateDependencyError) as exc_info:
        assemble.main(argv=[
            "--masterbook", str(masterbook_root),
            "--source", str(project / "CLAUDE.source.md"),
            "--out", str(project / "CLAUDE.md"),
        ])
    msg = str(exc_info.value)
    assert "paperwork-enforcement" in msg
    assert "session-paperwork" in msg
    assert "requires" in msg.lower()


def test_assemble_succeeds_with_both_substrates(tmp_path):
    """Opting into both substrates succeeds (this proves the dependency check
    isn't over-eager and doesn't false-positive)."""
    import sys
    from pathlib import Path
    ASSEMBLE = Path(__file__).resolve().parent.parent / "tools"
    if str(ASSEMBLE) not in sys.path:
        sys.path.insert(0, str(ASSEMBLE))
    import assemble

    REPO_ROOT = Path(__file__).resolve().parent.parent
    masterbook_root = REPO_ROOT

    project = tmp_path / "proj"
    project.mkdir()
    (project / "CLAUDE.source.md").write_text(
        "---\n"
        "masterbook:\n"
        "  modules: []\n"
        "  substrates: [session-paperwork, paperwork-enforcement]\n"
        "  permissions_extra: []\n"
        "  commands: []\n"
        "---\n"
        "body\n"
    )
    rc = assemble.main(argv=[
        "--masterbook", str(masterbook_root),
        "--source", str(project / "CLAUDE.source.md"),
        "--out", str(project / "CLAUDE.md"),
    ])
    assert rc == 0
